server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # Pas de cache pour HTML, CSS, JS
    location ~* \.(html|htm|css|js)$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
    }

    # Cache long pour images
    location ~* \.(jpg|jpeg|png|gif|svg|webp)$ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # FRONTEND TREASURER
    location /treasurer/ {
        alias /usr/share/nginx/html/treasurer/;
        index index.html;
        try_files $uri $uri/ /treasurer/index.html;
    }

    # API TREASURER
    location /treasurer-api/ {
        proxy_pass http://host.docker.internal:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}